imports:
    - { resource: Dao/services.yaml }
    - { resource: Events/services.yaml }
    - { resource: Service/services.yaml }
    - { resource: Utility/services.yaml }
    - { resource: ../Common/bootstrap-services.yaml }
    - { resource: ../Module/Install/bootstrap-services.yaml }
    - { resource: ../Module/MetaData/bootstrap-services.yaml }
    - { resource: ../Module/Configuration/bootstrap-services.yaml }
