services:
  OxidEsales\EshopCommunity\Internal\Templating\TemplateRendererInterface:
    class: OxidEsales\EshopCommunity\Internal\Templating\TemplateRenderer
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Templating\TemplateEngineInterface'
    public: true
    tags: ['templating']
  OxidEsales\EshopCommunity\Internal\Templating\TemplateEngineInterface:
    class: OxidEsales\EshopCommunity\Internal\Twig\TwigEngine
    autowire: true
    public: false
  OxidEsales\EshopCommunity\Internal\Templating\TemplateNameResolverInterface:
    class: OxidEsales\EshopCommunity\Internal\Templating\LegacyTemplateNameResolver
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Templating\TemplateNameResolver'
  OxidEsales\EshopCommunity\Internal\Templating\TemplateNameResolver:
    class: OxidEsales\EshopCommunity\Internal\Templating\TemplateNameResolver
  OxidEsales\EshopCommunity\Internal\Templating\FileLocator:
    class: OxidEsales\EshopCommunity\Internal\Templating\FileLocator
    arguments:
      - '@OxidEsales\Eshop\Core\Config'
      - '@OxidEsales\EshopCommunity\Internal\Templating\TemplateNameResolverInterface'
      - '@OxidEsales\EshopCommunity\Internal\Templating\EngineInterface'
  OxidEsales\EshopCommunity\Internal\Templating\AdminFileLocator:
    class: OxidEsales\EshopCommunity\Internal\Templating\AdminFileLocator
    arguments:
      - '@OxidEsales\Eshop\Core\Config'
      - '@OxidEsales\EshopCommunity\Internal\Templating\TemplateNameResolverInterface'
      - '@OxidEsales\EshopCommunity\Internal\Templating\EngineInterface'
  oxid_esales.templating.template.loader:
    class: OxidEsales\EshopCommunity\Internal\Templating\TemplateLoader
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Templating\FileLocator'
  oxid_esales.templating.admin.template.loader:
    class: OxidEsales\EshopCommunity\Internal\Templating\TemplateLoader
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Templating\AdminFileLocator'
