services:
  OxidEsales\Eshop\Core\Config:
    class: OxidEsales\Eshop\Core\Config
    factory: ['OxidEsales\Eshop\Core\Registry', getConfig]
    public: false
  OxidEsales\Eshop\Core\UtilsView:
    class: OxidEsales\Eshop\Core\UtilsView
    factory: ['OxidEsales\Eshop\Core\Registry', getUtilsView]
    public: false
  OxidEsales\EshopCommunity\Internal\Smarty\SmartyContextInterface:
    class: OxidEsales\EshopCommunity\Internal\Smarty\SmartyContext
    autowire: true
    public: false
  OxidEsales\EshopCommunity\Internal\Smarty\Configuration\SmartyConfigurationFactoryInterface:
    class: OxidEsales\EshopCommunity\Internal\Smarty\Configuration\SmartyConfigurationFactory
    autowire: true
    public: false
  OxidEsales\EshopCommunity\Internal\Smarty\Configuration\SmartySettingsDataProviderInterface:
    class: OxidEsales\EshopCommunity\Internal\Smarty\Configuration\SmartySettingsDataProvider
    autowire: true
    public: false
  OxidEsales\EshopCommunity\Internal\Smarty\Configuration\SmartySecuritySettingsDataProviderInterface:
    class: OxidEsales\EshopCommunity\Internal\Smarty\Configuration\SmartySecuritySettingsDataProvider
    autowire: true
    public: false
  OxidEsales\EshopCommunity\Internal\Smarty\Configuration\SmartyResourcesDataProviderInterface:
    class: OxidEsales\EshopCommunity\Internal\Smarty\Configuration\SmartyResourcesDataProvider
    autowire: true
    public: false
  OxidEsales\EshopCommunity\Internal\Smarty\Configuration\SmartyPrefiltersDataProviderInterface:
    class: OxidEsales\EshopCommunity\Internal\Smarty\Configuration\SmartyPrefiltersDataProvider
    autowire: true
    public: false
  OxidEsales\EshopCommunity\Internal\Smarty\Configuration\SmartyPluginsDataProviderInterface:
    class: OxidEsales\EshopCommunity\Internal\Smarty\Configuration\SmartyPluginsDataProvider
    autowire: true
    public: false
  OxidEsales\EshopCommunity\Internal\Smarty\Configuration\SmartyConfigurationInterface:
    class: OxidEsales\EshopCommunity\Internal\Smarty\Configuration\SmartyConfiguration
    factory: 'OxidEsales\EshopCommunity\Internal\Smarty\Configuration\SmartyConfigurationFactoryInterface:getConfiguration'
    public: false
  smarty.smarty_engine_factory:
    class: OxidEsales\EshopCommunity\Internal\Smarty\SmartyEngineFactory
    autowire: true
    public: true
  smarty.smarty_engine:
    class: OxidEsales\EshopCommunity\Internal\Smarty\SmartyEngine
    factory: 'smarty.smarty_engine_factory:getEngine'
    public: false
